version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mysql
      - redis
  php-fpm:
    container_name: photo_portflio_v2
    environment:
      PHP_IDE_CONFIG: "serverName=laravel05"

    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    #            - ./config/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - redis
  mysql:
    container_name: photo_portflio_db_v2
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wd05
  redis:
    image: redis:latest
